// <auto-generated />
using ASPQuiz10.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPQuiz10.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    partial class PeopleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASPQuiz10.Models.Person", b =>
                {
                    b.Property<string>("nameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("catName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dogName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nameId");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
